### ISSUE TITLE
Specyfikacja karty wideo

### ISSUE THREAD

**Issue by Dawiderter** [KN-Breadboard-Computing/computer#4]
Przygotowanie specyfikacji karty wideo. Co musi mieć i móc robić.

**Comment by Grubre** [comment]
## Instrukcje
1) `store byte at cursor` && `inc cursor x` && `cursor x mod 80` && `cursor y mod 60`
2) `store byte at cursor` && `inc cursor y` && `cursor x mod 80` && `cursor y mod 60`
3) `move cursor x|y` (w zależności od MSB)
4) `scroll up|down|left|right` (w zależności od [6:7])
5) *`clear`
6) *`display`
7) `store sprite byte` && `inc sprite cursor` && `sprite cursor mod 2048`
8) `store color byte` && `inc color cursor` && `color cursor mod 64`

**cursor** - 16 bitowy rejestr wskazujący adres do którego zapisujemy w buforze karty
\* - instrukcje mogą być zmergowane jako poszczególne ustawienia bitów w instrukcji 3

![videocard drawio](https://github.com/KN-Breadboard-Computing/computer/assets/69735117/9085227c-4bfa-4e4e-95ea-f4cf02b08110)
